# Generated by Django 3.2.12 on 2023-05-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.UUIDField()),
                ('status', models.BooleanField(default=True)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'environment',
            },
        ),
    ]
