# Generated by Django 3.2.12 on 2023-05-11 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 20, 21, 8, 367698)),
        ),
        migrations.AddField(
            model_name='environment',
            name='template',
            field=models.TextField(default=''),
        ),
    ]
