# Generated by Django 3.2.12 on 2023-05-11 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20230511_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 20, 25, 9, 368175)),
        ),
    ]
